### DISCUSSION TITLE
Make the Home Assistant Local Provider Appear First

### DISCUSSION THREAD

**Discussion by TheDuffman85** [christiaangoossens/hass-oidc-auth#30] [Ideas]
For me always the OIDC is shown as first option. I would like have Home Assistant Local first. How can I change the order of the auth providers? 

I tried to add it manually after the default provider, but without any luck. 

```
homeassistant:
  auth_providers:    
     - type: homeassistant
     - type: auth_oidc

auth_oidc:
  client_id: "someclientid"
  discovery_url: "somediscoveryurl"
```

I always see this provider first
![2025-01-14_22-40](https://github.com/user-attachments/assets/f11bf504-aa7a-4ba2-ae81-9465589cff27)

But i would like to see this first
![2025-01-14_22-40_1](https://github.com/user-attachments/assets/cd0d1c20-97d1-4919-936c-82a87982d24c)

Thank you for your great work!
