### ISSUE TITLE
automatic_user_linking not working with Zitadel

### ISSUE THREAD

**Issue by amasolov** [christiaangoossens/hass-oidc-auth#31]
Can't link existing HA users with my Zitadel users. 

HA has a local user with username test-user. HA config:
```
auth_oidc:
    client_id: "XXXXXXXXXXXXX"
    discovery_url: "https://sso.example.com/.well-known/openid-configuration"
    features:
      automatic_user_linking: true
      automatic_person_creation: false
```

Zitadel user info:
```
{
    "user": {
        "id": "302887194312310872",
        "state": "USER_STATE_ACTIVE",
        "userName": "test-user",
        "loginNames": [
            "test-user"
        ],
        "preferredLoginName": "test-user",
        "human": {
            "profile": {
                "firstName": "Test",
                "lastName": "User",
                "nickName": "test-user",
                "displayName": "Test User",
                "preferredLanguage": "en",
                "gender": "GENDER_MALE"
            },
            "email": {
                "email": "email@example.com",
                "isEmailVerified": true
            }
        }
    }
}
```

The debug logging in HA shows this:
```
2025-01-17 02:19:06.554 DEBUG (MainThread) [custom_components.auth_oidc.oidc_client] Obtained user details from OIDC provider: {'sub': '185efe92da07499a84c24e78b415c67265e91162c85eaae414502537f183a798', 'display_name': None, 'username': None, 'role': 'system-users'} (issuer subject: 302887194312310872)
```

I assume seeing matching issuer subject means it's authenticating with the correct user.
