### ISSUE TITLE
I don't even know how to help

### ISSUE THREAD

**Issue by Rihan9** [christiaangoossens/hass-oidc-auth#64]
Hi,
I was tring this addon to provide some feedbacks, but I don't even know where to start.

I'm receiving this as a login for:

![Image](https://github.com/user-attachments/assets/2e1b568e-0283-4207-bca9-a46746072941)

and it doesn't make any sense because it shouldn't ask me anything. I tried to insert my home assistant username (the same for the SSO btw), and tried to log in, but I received and empty error on the top.

from the network tab on my developer console I can see a call to:
https://homeassistant.example.com/auth/login_flow/c666a39e65ef8ffe890a355382ced291
with the following request:
```
{"code":"alessandro","client_id":"https://homeassistant.example.com/"}
```
and the following response:
```
{
    "type": "form",
    "flow_id": "c666a39e65ef8ffe890a355382ced291",
    "handler": [
        "auth_oidc",
        "default"
    ],
    "data_schema": [
        {
            "type": "string",
            "name": "code",
            "required": true
        }
    ],
    "errors": {
        "base": "invalid_auth"
    },
    "description_placeholders": null,
    "last_step": null,
    "preview": null,
    "step_id": "mfa"
}
```

I don't have the MFA configurated to authalia just jet, so I slightly changed my configuration. Does this make such an impact?

My home assistant configuration:
```
auth_oidc:
  client_id: "client_id"
  client_secret: "cient_secret"
  discovery_url: "https://auth.example.com/.well-known/openid-configuration"
```

my authelia configuration:
```
....
     - client_name: 'Home Assistant'
        client_id: 'client_id'
        client_secret: 'client_secret_ashed'
        public: false
        require_pkce: true
        pkce_challenge_method: 'S256'
        authorization_policy: 'one_factor'
        redirect_uris:
          - 'https://portal.example.com/auth/oidc/callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
        id_token_signed_response_alg: 'RS256'
        token_endpoint_auth_method: 'client_secret_post'
```

I don't see an error in the home assistant's log related to this, maybe I need to raise the debug level? Can you let me know witch one?
I don't see authelia called when I press that login button visible in the screenshot
